# V1版本提示词配置
# 章节总结提示词
chapterSummary:
  fiction: |
    请为以下章节内容生成一个详细总结：

    章节标题：{{title}}

    章节内容：
    {{content}}

    请用自然流畅的语言总结本章内容，包括主要情节发展、重要人物表现、关键观点或转折，以及本章在整个故事中的作用和意义。

    注意：如果内容是致谢、目录、前言、序言等无实质故事内容的页面，请直接回复"无需总结"。

    重要：请保持原文的段落结构和换行，不要删除或合并段落。
  
  nonFiction: |
    请为以下社科类书籍章节内容生成一个详细总结：

    章节标题：{{title}}

    章节内容：
    {{content}}

    请用自然流畅的语言总结本章内容，包括：

    - 主要观点，以及支持这个观点的案例或研究发现
    - 关键概念
    - 保留几句有洞见的观点原文
    - 给出指导实际生活的建议或应用（必须与此章节内容强关联）

    重要：请保持原文的段落结构和换行，不要删除或合并段落。

# 思维导图提示词
mindmap:
  chapter: |
    ```ts
    export interface NodeObj {
      topic: string
      id: string
      tags?: string[]
      children?: NodeObj[]
    }
    // 总结父id的第start到end个节点的内容
    export interface Summary {
      id: string
      label: string
      /**
       * parent node id of the summary
       */
      parent: string
      /**
       * start index of the summary
       */
      start: number
      /**
       * end index of the summary
       */
      end: number
    }
    ```

    使用符合  {
      nodeData: NodeObj
      summaries?: Summary[]
    } 格式的 JSON 回复用户，这是一个表达**思维导图数据**的递归结构。

    **注意！！nodeData、summaries 在同一层级！！**

    **严格遵守**：
    - 节点 ID 使用递增数字即可
    - 注意不要一昧使用兄弟节点关系，适当应用父子级别的分层
    - 向节点插入 tags 可选：核心、案例、实践、金句
    - Summary 是总结多个同父节点的子节点的工具，会使用花括号把总结文本显示在指定子节点侧边，因为节点存在两侧分布的情况，禁止总结根节点
    - 适当添加 Summary，不要添加多余的 Summary
    - 最后添加一个金句节点记录几句本章金句
    - 适当添加表达该节点内涵的 emoji
    - 确保JSON格式正确，不要返回任何JSON以外的内容
    - 如果内容是致谢、目录、前言、序言、参考文献、出版社介绍、引用说明等的页面，请直接回复"{nodeData:null}"

  arrow: |
    你需要为已有的思维导图添加箭头连接，以显示不同节点之间的关联关系。
    ```ts
    export interface NodeObj {
      topic: string
      id: string
      tags?: string[]
      children?: NodeObj[]
    }

    export interface Arrow {
      id: string
      /**
       * label of arrow
       */
      label: string
      /**
       * id of start node
       */
      from: string
      /**
       * id of end node
       */
      to: string
      /**
       * offset of control point from start point
       */
      delta1: {
        x: number
        y: number
      }
      /**
       * offset of control point from end point
       */
      delta2: {
        x: number
        y: number
      }
      /**
       * whether the arrow is bidirectional
       */
      bidirectional?: boolean
    }
    ```

    使用符合  {
      arrows?: Arrow[]
    } 格式的 JSON 回复用户。


    **严格遵守**：
    - Arrow 可以添加连接任意节点的箭头，label 间接说明两个节点的联系，delta 的默认值为 50,50。**直接的父子关系不需要链接**
    - **直接的父子关系不需要使用 Arrow 链接**
    - 只能添加 6 条以下 Arrow，请对最关键的节点关系进行链接
    - 确保JSON格式正确，不要返回任何JSON以外的内容

  combined: |
    请将以下所有章节内容整合为一个完整的思维导图：

    ```ts
    export interface NodeObj {
      topic: string
      id: string
      tags?: string[]
      children?: NodeObj[]
    }
    // 总结父id的第start到end个节点的内容
    export interface Summary {
      id: string
      label: string
      /**
       * parent node id of the summary
       */
      parent: string
      /**
       * start index of the summary
       */
      start: number
      /**
       * end index of the summary
       */
      end: number
    }
    ```

    使用符合  {
      nodeData: NodeObj
      summaries?: Summary[]
    } 格式的 JSON 回复用户，这是一个表达**整书思维导图数据**的递归结构。

    **注意！！nodeData、summaries 在同一层级！！**

    **严格遵守**：
    - 以书籍主题作为根节点，各章节作为主要分支
    - 节点 ID 使用递增数字即可
    - 注意章节之间的逻辑关系和层次结构
    - 向节点插入 tags 可选：核心、案例、实践、金句
    - Summary 是总结多个同父节点的子节点的工具
    - 适当添加 Summary，不要添加多余的 Summary
    - 适当添加表达该节点内涵的 emoji
    - 确保JSON格式正确，不要返回任何JSON以外的内容

# 章节关联分析提示词
connectionAnalysis: |
  请帮我分析这本书各章节之间的关系，并总结全书的核心内容：

  {{chapterSummaries}}

  请从以下几个方面来分析：

  ## 1. 章节之间的联系
  - 各章节是如何一步步展开论述的？
  - 哪些重要观点在不同章节中反复出现？
  - 前面的章节为后面的内容做了哪些铺垫？

  ## 2. 全书的核心主题
  - 这本书最想告诉读者什么？
  - 作者的主要观点是什么？
  - 有哪些值得特别关注的重要概念？

  ## 3. 实用价值
  - 这本书对现实生活有什么指导意义？
  - 读者可以从中学到什么实用的知识或方法？
  - 哪些观点可能会改变我们的思考方式？

  ## 4. 简明总结
  - 用几句话概括这本书的精华
  - 推荐给什么样的人阅读
  - 阅读这本书的最大收获是什么

  请用通俗易懂的语言来分析，让普通读者也能轻松理解书籍的价值和意义。

# 全书总结提示词
overallSummary: |
  书籍章节结构：
  {{chapterInfo}}

  章节关联分析：
  {{connections}}

  以上是《{{bookTitle}}》这本书的重点内容，请生成一个全面的总结报告，帮助读者快速掌握全书精髓。

# 其他系统提示词
system:
  testConnection: "这是一个连接测试。请简单回复\"OK\"，不要添加任何其他文字、标点符号或格式。"
